// import c from './index'

const c = require('./index')

c.p('purple')
c.b('blue')
c.c('cyan')
c.g('green')
c.y('yellow')
c.o('orange')
c.m('magenta')
c.r('red')

c.pb('purple background')
c.bb('blue background')
c.cb('cyan background')
c.gb('green background')
c.yb('yellow background')
c.ob('orange background')
c.mb('magenta background')
c.rb('red background')

c.ph('purple header')
c.bh('blue header')
c.ch('cyan header')
c.gh('green header')
c.yh('yellow header')
c.oh('orange header')
c.mh('magenta header')
c.rh('red header')

c.pbh('purple background + header')
c.bbh('blue background + header')
c.cbh('cyan background + header')
c.gbh('green background + header')
c.ybh('yellow background + header')
c.obh('orange background + header')
c.mbh('magenta background + header')
c.rbh('red background + header')
